"""add bonus_pay to salary_records

Revision ID: 0e7b4c2fe536
Revises: 7830c4aadf24
Create Date: 2026-09-07 21:42:19.963918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e7b4c2fe536'
down_revision: Union[str, Sequence[str], None] = '7830c4aadf24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 기존 행에는 상여금 정보가 없으므로 server_default로 0을 채운다. 이후 삽입되는 행은 ORM이
    # 항상 값을 명시적으로 채우므로(app/services/records.py) server_default는 실질적으로
    # 과거 행을 위한 백필 용도로만 남는다.
    op.add_column(
        'salary_records', sa.Column('bonus_pay', sa.Integer(), nullable=False, server_default='0')
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary_records', 'bonus_pay')
    # ### end Alembic commands ###
