"""initial schema

Revision ID: 7830c4aadf24
Revises: 
Create Date: 2026-08-30 10:31:27.888621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7830c4aadf24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('security_question', sa.String(), nullable=False),
    sa.Column('security_answer_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('salary_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('employee_name', sa.String(), nullable=False),
    sa.Column('gross_pay', sa.Integer(), nullable=False),
    sa.Column('num_dependents', sa.Integer(), nullable=False),
    sa.Column('num_children_8_to_20', sa.Integer(), nullable=False),
    sa.Column('national_pension', sa.Integer(), nullable=False),
    sa.Column('health_insurance', sa.Integer(), nullable=False),
    sa.Column('long_term_care', sa.Integer(), nullable=False),
    sa.Column('employment_insurance', sa.Integer(), nullable=False),
    sa.Column('income_tax', sa.Integer(), nullable=False),
    sa.Column('local_income_tax', sa.Integer(), nullable=False),
    sa.Column('total_deduction', sa.Integer(), nullable=False),
    sa.Column('net_pay', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_records_id'), 'salary_records', ['id'], unique=False)
    op.create_index(op.f('ix_salary_records_owner_id'), 'salary_records', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_records_owner_id'), table_name='salary_records')
    op.drop_index(op.f('ix_salary_records_id'), table_name='salary_records')
    op.drop_table('salary_records')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
