"""add login lockout fields to users

Revision ID: e69b1628bedc
Revises: 0e7b4c2fe536
Create Date: 2026-09-19 20:41:33.779083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e69b1628bedc'
down_revision: Union[str, Sequence[str], None] = '0e7b4c2fe536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 기존 사용자 행에는 잠금 이력이 없으므로 0으로 채운다(bonus_pay 마이그레이션과 동일하게
    # server_default를 영구히 남겨, SQLite의 ALTER COLUMN 제약을 피한다).
    op.add_column(
        'users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0')
    )
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
